# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: amirulandalib
          template: classic
          base: header, activity, community, repositories, metadata
          commits_authoring: amirulandalib@gmailc.om
          config_order: base.header, base.repositories
          config_timezone: Asia/Dhaka
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_limit: 0
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
          plugin_activity: yes
          plugin_activity_days: 20
          plugin_activity_filter: all
          plugin_activity_limit: 20
          plugin_activity_load: 100
          plugin_activity_timestamps: yes
          plugin_activity_visibility: all
          plugin_code: yes
          plugin_code_lines: 20
          plugin_code_load: 100
          plugin_code_visibility: all
          plugin_discussions: yes
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_gists: yes
          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 20
          plugin_habits_facts: yes
          plugin_habits_from: 100
          plugin_habits_trim: yes
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: yes
          plugin_languages_limit: 20
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 20
          plugin_languages_recent_load: 100
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_lines: yes
          plugin_notable: yes
          plugin_notable_repositories: yes
          plugin_people: yes
          plugin_people_limit: 50
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_days: 0
          plugin_reactions_details: count
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_reactions_limit: 200
          plugin_reactions_limit_issues: 100
          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_batch: 125
          plugin_repositories_featured: xcodershub/tortoolkitx, xcodershub/torrentleechx, XcodersHub/GdriveTools
          plugin_repositories_forks: yes
          plugin_skyline: yes
          plugin_skyline_frames: 60
          plugin_skyline_quality: 0.1
          plugin_skyline_year: 2021
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 50
          plugin_stock: yes
          plugin_stock_duration: 1d
          plugin_stock_interval: 5m
          plugin_traffic: yes
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}      # Required
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 25
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_url: https://wakatime.com/@AmirulAndalib
          plugin_wakatime_user: .user.login                         # User
          repositories: 150
          repositories_batch: 125
          repositories_forks: yes
